import streamlit as st
import joblib
import numpy as np
import pandas as pd
import os
import warnings
from src.preprocess import clean_text
from scraper_test import scrape_amazon_reviews
from sklearn.pipeline import make_pipeline

# --- 1. VERSION GUARD & CONFIG ---
# Suppress the InconsistentVersionWarning to prevent logs from bloating
from sklearn.exceptions import InconsistentVersionWarning
warnings.filterwarnings("ignore", category=InconsistentVersionWarning)

st.set_page_config(page_title="AI Review Analyser", layout="wide", page_icon="🛡️")

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
MODEL_PATH = os.path.join(BASE_DIR, "model", "fake_review_model.pkl")

@st.cache_resource
def load_model_assets():
    if not os.path.exists(MODEL_PATH):
        st.error(f"❌ Model file NOT found at: {MODEL_PATH}")
        st.stop()

    try:
        # Load with a fallback for version differences
        loaded_data = joblib.load(MODEL_PATH)
        
        if isinstance(loaded_data, (tuple, list)) and len(loaded_data) == 2:
            model_obj, vectorizer_obj = loaded_data[0], loaded_data[1]
        else:
            model_obj, vectorizer_obj = loaded_data, None 
            
        return model_obj, vectorizer_obj
    except Exception as e:
        st.error(f"Internal Load Error: {e}")
        st.info("Tip: If you see a 'ModuleNotFoundError', ensure scikit-learn version matches your training env.")
        st.stop()

model, vectorizer = load_model_assets()

# Build pipeline for analysis
try:
    if vectorizer is not None:
        c = make_pipeline(vectorizer, model)
    else:
        c = model  # Assumes it was already a Pipeline
except Exception as e:
    st.error(f"Pipeline Creation Error: {e}")
    st.stop()

# --- 2. CORE ANALYSIS ENGINE ---
def run_analysis(review_text, rating=None):
    cleaned = clean_text(review_text)
    words = cleaned.split()
    
    if len(words) == 0:
        return None

    # Get probability scores
    probs = c.predict_proba([cleaned])[0]
    prediction_index = np.argmax(probs) # 0 = Fake (CG), 1 = Real (OR)
    ai_real_confidence = probs[1] * 100
    
    # Calculate unique word ratio to catch simple bot repetition
    unique_ratio = len(set(words)) / len(words)
    is_fake = (prediction_index == 0) or (unique_ratio < 0.15)
    
    # BEHAVIORAL ANALYSIS: Detecting "Intentional Misinformation"
    intentional_malice = False
    if rating is not None:
        malicious_keywords = ['bad', 'worst', 'scam', 'fake', 'trash', 'waste', 'cheap', 'fraud']
        # Flag 1: AI says it's real, but user gave 1-star and used heavy negative bias keywords
        if prediction_index == 1 and rating <= 2.0 and any(kw in cleaned.lower() for kw in malicious_keywords):
            intentional_malice = True
        # Flag 2: 5-star rating but text contains "waste of money"
        if prediction_index == 1 and rating >= 4.5 and "waste" in cleaned.lower():
            intentional_malice = True

    return {
        "is_fake": is_fake,
        "intentional": intentional_malice,
        "confidence": ai_real_confidence,
        "cleaned_text": cleaned
    }

# --- 3. UI LAYOUT ---
st.title("🛡️ AI Product Integrity System")
st.markdown("Analyze live reviews for bot-spam and intentional misinformation.")

tab1, tab2 = st.tabs(["📝 Single Review Check", "🌐 Global Product Analysis"])

with tab1:
    st.subheader("Manual Analysis")
    manual_review = st.text_area("Paste a review here:", height=150, key="manual_input")
    if st.button("Analyze Review", key="manual_btn"):
        if manual_review:
            res = run_analysis(manual_review)
            if res:
                if res["is_fake"]: 
                    st.error("### 🚩 VERDICT: FAKE / BOT GENERATED")
                else: 
                    st.success("### ✅ VERDICT: GENUINE")
                
                col_a, col_b = st.columns(2)
                col_a.metric("AI Confidence", f"{res['confidence']:.1f}%")
                col_b.metric("Intentional Malice", "Yes" if res['intentional'] else "No")

with tab2:
    st.subheader("Live Amazon Search")
    product_name = st.text_input("Enter Product Name (e.g. 'Logitech G502'):", key="p_name")

    if st.button("Search & Analyze Across Platforms", key="search_btn"):
        if product_name:
            # Placeholder for debugging screenshot
            debug_placeholder = st.empty()
            
            with st.spinner(f"Scraping Amazon for '{product_name}'..."):
                scraped_data = scrape_amazon_reviews(product_name)
            
            # --- SCRAPING ERROR HANDLING ---
            if not scraped_data:
                st.error("🚨 Scraping Failed or Blocked.")
                st.warning("Amazon likely detected a bot. Check the image below for CAPTCHA or 'Robot Check'.")
                
                # Check for the debug screenshot generated by scraper_test.py
                if os.path.exists("bot_check.png"):
                    st.image("bot_check.png", caption="Last Browser State (Debugging)")
                else:
                    st.info("No debug screenshot available. Ensure your scraper saves 'bot_check.png' on failure.")
            else:
                # --- DATA PROCESSING ---
                total = len(scraped_data)
                fakes = 0
                malice = 0
                table_rows = []

                for item in scraped_data:
                    analysis = run_analysis(item['text'], rating=item['rating'])
                    if not analysis: continue
                    if analysis['is_fake']: fakes += 1
                    if analysis['intentional']: malice += 1
                    
                    table_rows.append({
                        "Rating": f"{item['rating']} ⭐",
                        "Review Snippet": item['text'][:80] + "...",
                        "AI Verdict": "🚩 FAKE" if analysis['is_fake'] else "✅ REAL",
                        "Behavioral Alert": "⚠️ MALICIOUS" if analysis['intentional'] else "Normal"
                    })

                # --- RESULTS DISPLAY ---
                st.divider()
                st.header(f"Trust Report for: {product_name}")
                col1, col2, col3 = st.columns(3)
                
                auth_score = int(((total - fakes) / total) * 100) if total > 0 else 0
                
                col1.metric("Reviews Analyzed", total)
                col2.metric("Authenticity Score", f"{auth_score}%")
                col3.metric("Malicious Intent Found", malice)

                st.subheader("📑 Detailed Breakdown")
                st.dataframe(pd.DataFrame(table_rows), use_container_width=True)
        else:
            st.warning("Please enter a product name.")
